before_install:
  - echo "$(ant -version)"

language: java

matrix:
  include:
    - dist: trusty
      jdk: openjdk8
    - dist: trusty
      jdk: openjdk7
    - dist: precise
      jdk: openjdk6

script: ant -lib vendor/buildlib test